


I changed all the paths and installed (I think) all of the packages. When i run bash ./test.sh  though it has some sort of error that I can't sort out.

Part of the error:
CalledProcessError in line 203 of /home/edanner/workspace/pigx_crispr/pigx_crispr.py:
Command ' set -euo pipefail;  /home/edanner/anaconda3/bin/Rscript /home/edanner/workspace/pigx_crispr/src/runReport.R  --reportFile=/home/edanner/workspace/pigx_crispr/src/report.Rmd --ampliconFastaFile=/home/edanner/workspace/pigx_crispr/sample_data/amplicons/amplicon_lin-41.fa --ampliconName=lin-41 --cutSitesFile=/home/edanner/workspace/pigx_crispr/sample_data/cutsites/sgRNA_cutsites_lin-41.txt --sampleSheetFile=/home/edanner/workspace/pigx_crispr/sample_data/sample_sheet.csv --indelsFolder=/home/edanner/workspace/pigx_crispr/sample_data/output/indels/lin-41 --workdir=/home/edanner/workspace/pigx_crispr/sample_data/output/reports --prefix=lin-41 > /home/edanner/workspace/pigx_crispr/sample_data/output/logs/lin-41.report.log 2>&1 ' returned non-zero exit status 1.
  File "/home/edanner/workspace/pigx_crispr/pigx_crispr.py", line 203, in __rule_report
  File "/home/edanner/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run

